services:
  - type: web
    name: strapi-backend
    env: node
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: sqlite
